name: movies_app
description: "A new Flutter project."

# ÙŠÙ…Ù†Ø¹ Ù†Ø´Ø± Ø§Ù„Ø­Ø²Ù…Ø© Ø¹Ù„Ù‰ pub.dev
publish_to: 'none'

# Ø±Ù‚Ù… Ø§Ù„Ø¥ØµØ¯Ø§Ø±
version: 1.0.0+1

# Ø¨ÙŠØ¦Ø© Ø§Ù„Ù€ SDK Ø§Ù„Ù…Ø·Ù„ÙˆØ¨Ø©
environment:
  sdk: ^3.6.0

# ğŸ“Œ Ø§Ù„Ø­Ø²Ù… Ø§Ù„Ù…Ø·Ù„ÙˆØ¨Ø© ÙÙŠ Ø§Ù„Ù…Ø´Ø±ÙˆØ¹
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  introduction_screen: ^3.1.14
  shared_preferences: ^2.4.0
  carousel_slider: ^5.0.0
  video_player: ^2.9.2
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  url_launcher: ^6.2.5
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ğŸ“Œ Ø¥Ø¶Ø§ÙØ© Ø§Ù„Ù…Ù„ÙØ§Øª ÙˆØ§Ù„ØµÙˆØ± Ø¥Ù„Ù‰ Ø§Ù„ØªØ·Ø¨ÙŠÙ‚
  assets:
    - assets/
    - assets/images/
    - assets/icons/
